version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "hack3d"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(actions):"
      prefix-development: "chore(actions):"
      include: "scope"
