name: Build OPM

on:
  push:
    branches:
      - main

    tags:
      - 'v*'

  pull_request:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'

      - name: Perl Lint
        run: |
          find Kernel -type f -name "*.pm" | while read FILE
          do
            perl -c "$FILE"
          done

  build:

    needs: lint

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/znuny/znuny-docker/znuny-base:7.3.5
    steps:
      - uses: actions/checkout@v4

      - name: Build OPM
        run: |
          pwd
          ls -l 
          ls -l ${{ github.workspace }}
          cp /opt/znuny/Kernel/Config.pm.dist /opt/znuny/Kernel/Config.pm
          su -c "/opt/znuny/bin/znuny.Console.pl Dev::Package::Build ${{ github.workspace }}/OAuth2AuthSync.sopm /tmp" -s /bin/bash znuny

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: OAuth2AuthSync
          path: /tmp/*.opm

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: OAuth2AuthSync
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.zip