name: Build OPM

on:
  push:
    branches:
      - main

    tags:
      - 'v*'

  pull_request:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'

      - name: Perl Lint
        run: |
          find Kernel -type f -name "*.pm" | while read FILE
          do
            perl -c "$FILE"
          done

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/znuny/znuny-docker/znuny-base:7.3.5
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Znuny
        run: |
          cd /opt/znuny
          cp Kernel/Config.pm.dist Kernel/Config.pm
          mkdir /opt/znuny/Kernel/System/AuthSync
          cp ${GITHUB_WORKSPACE}/Kernel/System/AuthSync/OAuth2AuthSync.pm /opt/znuny/Kernel/System/AuthSync/OAuth2AuthSync.pm
          cp ${GITHUB_WORKSPACE}/Kernel/Config/Files/XML/OAuth2AuthSync.xml /opt/znuny/Kernel/Config/Files/XML/OAuth2AuthSync.xml
          cp -R ${GITHUB_WORKSPACE}/scripts/test/OAuth2AuthSync/ /opt/znuny/scripts/test/OAuth2AuthSync/

      - name: Run Unit Tests - AccessToken
        run: |
          su -c "/opt/znuny/bin/znuny.Console.pl Dev::UnitTest::Run --test OAuth2AuthSync --test AccessToken" -s /bin/bash znuny
      
      - name: Run Unit Tests - GroupMapping
        run: |
          su -c "/opt/znuny/bin/znuny.Console.pl Dev::UnitTest::Run --test OAuth2AuthSync --test GroupMapping" -s /bin/bash znuny
        
      - name: Run Unit Tests - Install
        run: |
          su -c "/opt/znuny/bin/znuny.Console.pl Dev::UnitTest::Run --test OAuth2AuthSync --test Install" -s /bin/bash znuny

      - name: Run Unit Tests - LoginPriority
        run: |
          su -c "/opt/znuny/bin/znuny.Console.pl Dev::UnitTest::Run --test OAuth2AuthSync --test LoginPriority" -s /bin/bash znuny
 
      - name: Run Unit Tests - ProtectedUsers
        run: |
          su -c "/opt/znuny/bin/znuny.Console.pl Dev::UnitTest::Run --test OAuth2AuthSync --test ProtectedUsers" -s /bin/bash znuny
 

  build:
    needs:
      - lint
      - test

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/znuny/znuny-docker/znuny-base:7.3.5
    steps:
      - uses: actions/checkout@v4

      - name: Build OPM
        run: |
          cp /opt/znuny/Kernel/Config.pm.dist /opt/znuny/Kernel/Config.pm
          mkdir /opt/znuny/Kernel/System/AuthSync
          cp ${GITHUB_WORKSPACE}/Kernel/System/AuthSync/OAuth2AuthSync.pm /opt/znuny/Kernel/System/AuthSync/OAuth2AuthSync.pm
          cp ${GITHUB_WORKSPACE}/Kernel/Config/Files/XML/OAuth2AuthSync.xml /opt/znuny/Kernel/Config/Files/XML/OAuth2AuthSync.xml
          su -c "/opt/znuny/bin/znuny.Console.pl Dev::Package::Build ${GITHUB_WORKSPACE}/OAuth2AuthSync.sopm /tmp" -s /bin/bash znuny

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: OAuth2AuthSync
          path: /tmp/*.opm

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v8
        with:
          name: OAuth2AuthSync
          path: release

      - name: Check download
        run: |
          pwd
          ls -l release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: release/*.opm